services:
  fks_execution:
    build:
      context: .
      dockerfile: Dockerfile
    networks: [fks_net]
    healthcheck:
      test: ["CMD-SHELL", "python -c 'print(1)' || exit 1"]
      interval: 45s
      timeout: 5s
      retries: 2
      start_period: 30s

networks:
  fks_net:
    name: fks_net